### ISSUE TITLE
Suggestion/Fix Novel

### ISSUE THREAD

**Issue by OtakuVadER** [RepoDevil/Himitsu#14]
Okay so my suggestion is that like aniyomi extension 
There is Lnreader for novel so if you can implement that source list into app it should do the work and it's better than old sources because they doesn't need to be downloaded first(which is case in current extension)

Link for source: https://github.com/LNReader/lnreader-plugins

These are the plugins
Please look into it

**Comment by AbandonedCart** [comment]
I made the repository configurable like anime and manga. It's a start.

**Comment by OtakuVadER** [comment]
Yea so it can be added and there is already novel reader

**Comment by AbandonedCart** [comment]
Did novels used to work? I hadn't touched that beyond the install process and testing it now, it does seem very broken.

**Comment by OtakuVadER** [comment]
Indeed they used to work but it was the worst implementation i had ever seen
First you gotta select extension which we had 2 then for example i want to read classroom of the elite novel vol 1 so after selecting extension when we click chapter the first thing we gotta choose is our source
Just like there is you know different streams to select from but in here you gotta download the epub file then it will work
So it's cons were : 
Slow download (literally takes 5-10mins)
Storage issue in long term
And now it's very very broken

**Comment by AbandonedCart** [comment]
Alright. I fixed their attempt to merge it with the regular extension code. I merged the reader with manga. The other source looks to be proprietary to their app so I'm not entirely sure about being able to support that, but I'm fixing the whole download thing. That's a bit of a mess.

**Comment by AbandonedCart** [comment]
Unfortunately, an epub (the book format) is like a cbr / cbz for comics. It's a zip file. How a lot of the comic and manga sites work is by providing the option to get the contents through an online directory so you don't have to download the whole zip first. An epub more or less has to be downloaded.

**Comment by OtakuVadER** [comment]
So it can't be supported??

**Comment by AbandonedCart** [comment]
It means you'll still have to do the downloads

**Comment by OtakuVadER** [comment]
But how does light novel reader gives is ability to directly read novel?

**Comment by OtakuVadER** [comment]
Can you make download system of novel like that i selected the source and it will open with downloading in the background and with the amount of page downloaded we can read them and the moment we jave completed the volume and we leave player epub file gets deleted

**Comment by AbandonedCart** [comment]
It's a zip file. I don't think there is a way top open part of a zip file as it downloads.

**Comment by OtakuVadER** [comment]
Yea reasonable!.

**Comment by AbandonedCart** [comment]
There's still a lot to work out, but I am able to load the plugins from lnreader as extensions

**Comment by OtakuVadER** [comment]
Cool looking forward to the final results

**Comment by OtakuVadER** [comment]
It's completed?

**Comment by AbandonedCart** [comment]
It's ugly, but mostly supported. The rest is cleaning it up. The plugins are node wrappers for the sites, so the only way to natively support them would be react native. They're also not files. It's all text written as regular website pages. The next best thing was a way to open a novel from a site and create a file from it that could be loaded in a reader.

**Comment by OtakuVadER** [comment]
Am unable to understand how to use plugins thou

**Comment by AbandonedCart** [comment]
That's the part that needs cleaning up.

**Comment by OtakuVadER** [comment]
Ohkkkkk

**Comment by AbandonedCart** [comment]
The plugins are actually a bit of a disappointment. A lot of pay walls

**Comment by AbandonedCart** [comment]
Once it finishes building, the newest version will let you open the extension page and plugins will be in the plugin tab. Click the browser icon next to one, find a novel you want, and click read first. It will collect all the pages into a download.

It's ugly, but it gets the content. Still needs a way to package that up into an epub or a viewer to read it normally, some way to search without the sites needing to be opened, and a way to save in the background instead of showing as it reads the pages.

It's probably never going to be pretty for viand reason LNReader doesn't use tachiyomi extensions. The two styles aren't really compatible. Probably would have been easier to make extensions for all the sites individually.

**Comment by OtakuVadER** [comment]
Demn making every extension is gonna take a lot of time but choosing 6-7 good ones should do the trick ig and if someone want then can just open a pr to add new extensions

**Comment by OtakuVadER** [comment]
I mean if you have no idea what to work on next try this then...
If you don't wish to that's okay!!

**Comment by AbandonedCart** [comment]
Ill support extensions, but I'm definitely not making them. That's a job for someone who knows more about the content.

**Comment by OtakuVadER** [comment]
Ohk got it
