### ISSUE TITLE
Search history bug 

### ISSUE THREAD

**Issue by FeeninForMore** [RepoDevil/Himitsu#17]
There's a bug what makes your keyboard not pop up automatically when you have too many search history names

**Comment by AbandonedCart** [comment]
Is this in search? Normally you'd want your keyboard there.

**Comment by FeeninForMore** [comment]
Anime and manga search

**Comment by FeeninForMore** [comment]
It's a bug with dantotsu, I reported it to rebel and he said the bug is not in his priorities and just left it. It's been there since the beginning of the app

**Comment by AbandonedCart** [comment]
That sounds like them, but I misread the original issue. I didn't see you said that it **doesn't** pop up. That's why I was confused.

**Comment by FeeninForMore** [comment]
A bit off topic but I don't understand why they keep on adding features instead of actually fixing current bugs, rebels excuse is because they're low priority which is dumb

**Comment by AbandonedCart** [comment]
This should be solved in the next build.
