### ISSUE TITLE
[Request] Ability to search other Things which anilist offers!!

### ISSUE THREAD

**Issue by OtakuVadER** [RepoDevil/Himitsu#19]
Yo an suggestion after a long time!

So an ability to search a profile or staff or studio in app itself just like original anilist tracking should have!!

So you think it's possible?

**Comment by AbandonedCart** [comment]
It's already been requested in the Discord.

**Comment by OtakuVadER** [comment]
Yea ik it's already asked their i told them lemme open a issue here an issue is always important to mark progress 😅

**Comment by OtakuVadER** [comment]
Btw i wanna talk to you abt smtg so how can i contact you ?
What's your discord id?

**Comment by AbandonedCart** [comment]
You'd have to leave a message with the bot. Mine are disabled.

**Comment by OtakuVadER** [comment]
Umm how??

**Comment by OtakuVadER** [comment]
What @ of bot?

**Comment by AbandonedCart** [comment]
<@297916343792041984>

**Comment by AbandonedCart** [comment]
Search for other things kinda sucks. It finds the single closest match.

**Comment by OtakuVadER** [comment]
What u wanted to talk to you about was that there a dev who is making hdo pro mod version would you like to help him??

**Comment by OtakuVadER** [comment]
> Search for other things kinda sucks. It finds the single closest match.

Even if you gets data from anilist still that persists??

**Comment by AbandonedCart** [comment]
> What u wanted to talk to you about was that there a dev who is making hdo pro mod version would you like to help him??

I have a lot going on already

> Even if you gets data from anilist still that persists??

It's their search that is bad

**Comment by AbandonedCart** [comment]
I found a way to go about it, but it would require making multiple queries. That would be a very costly search. The issue is that searching, for example, a character will only return the id of the character. You have to perform a second operation to get their name, picture, etc. Let's say you return 20 characters. That's 21 queries.

**Comment by OtakuVadER** [comment]
How does other Anilist tracking app does it can't you see what they do to replicate smtg like that?

**Comment by AbandonedCart** [comment]
Multiple queries.

**Comment by OtakuVadER** [comment]
So that's the option in the end 🫡

**Comment by AbandonedCart** [comment]
That and the app has almost no support for any of the data.

**Comment by OtakuVadER** [comment]
You gotta refactor to support these things smoothly

**Comment by AbandonedCart** [comment]
How do you do that?

**Comment by OtakuVadER** [comment]
Adding more support and changing whole lot of code and ig change ui to accomodate changes to make sure app look clean

**Comment by AbandonedCart** [comment]
Yeah, but how?

**Comment by AbandonedCart** [comment]
Anyway… this would require a huge rewrite. It is something that will be slowly tested and / or progressed in the background.

**Comment by OtakuVadER** [comment]
Will be added slowly few things at a time?

**Comment by AbandonedCart** [comment]
![pending](https://github.com/RepoDevil/Himitsu/assets/1173913/c5414bb6-8343-4981-be27-b192b2f88109)

**Comment by OtakuVadER** [comment]
Mr mechanic on work 🫡🫡

**Comment by AbandonedCart** [comment]
This one is big. I keep adding bits between other small changes, but it needs needs a lot of UI. The rest is essentially done.

**Comment by OtakuVadER** [comment]
Backwork is done so you just need to create UI to show it cool Little by little it will all be done!!

**Comment by AbandonedCart** [comment]
Doing some tests and wrapping this one up.

**Comment by OtakuVadER** [comment]
UI is completed?

**Comment by AbandonedCart** [comment]
Yes

**Comment by OtakuVadER** [comment]
Available in new apk?
I wanna test it out!

**Comment by AbandonedCart** [comment]
Doing some tests first.

**Comment by AbandonedCart** [comment]
It's the search option labeled P/P/T (person, place, or thing) next to image search in the regular search page.

**Comment by OtakuVadER** [comment]
Ohk cool
