### ISSUE TITLE
Episode number bug

### ISSUE THREAD

**Issue by TheSolution444** [RepoDevil/Himitsu#20]
I have a strange bug which switches the latest episode and total episodes. Trending scroller also does not show the status properly. It just says "STATUS".
![Screenshot_20240504-113745~2.png](https://github.com/RepoDevil/Himitsu/assets/161716107/37527d95-87fd-4662-822a-0c253037ee7f)

**Comment by AbandonedCart** [comment]
It's not a bug. It's "watched | total | upcoming"

**Comment by TheSolution444** [comment]
> It's not a bug. It's "watched | total | upcoming"

Oh I understand now. My bad. And thanks

**Comment by AbandonedCart** [comment]
No worries. It's different and there aren't any labels.

**Comment by AbandonedCart** [comment]
Fixed in 9d8705f1
