### ISSUE TITLE
[Feature Request] Applock

### ISSUE THREAD

**Issue by Mathew20kdroid** [RepoDevil/Himitsu#34]
- Please add an option to **lock the App** please....
- In addition please add an option to hide the **recents preview** as well...

**Comment by AbandonedCart** [comment]
Do you have a fingerprint reader on your phone?

**Comment by Mathew20kdroid** [comment]
Yes

**Comment by AbandonedCart** [comment]
Alright. Let me see what I can do.

**Comment by AbandonedCart** [comment]
Need to add a couple UI things and test to make sure it works on a live device, but this is essentially done.

**Comment by Mathew20kdroid** [comment]
Awesome

**Comment by AbandonedCart** [comment]
It will be enabled under settings -> system. If you don't have any fingerprints registered, it will still let you into the app with an error message (since you have to be authenticated to remove them). Doing some last minute cleanup and then it will be live.

**Comment by Mathew20kdroid** [comment]
I just installed the update and the Applock work...

Can you please make it so that the home screen or app loads after the **fingerprint or biometric has been confirmed**

**Comment by AbandonedCart** [comment]
The best I can do is black it out, but not loading will create a *massive* bottleneck.

**Comment by AbandonedCart** [comment]
It's filtered through Discord, but we're also asking everyone to stop referencing this fork in issue reports to other projects. It may be misinterpreted as mocking.

**Comment by Mathew20kdroid** [comment]
Sorry😓

**Comment by AbandonedCart** [comment]
No worries. I know it wasn't meant that way.

**Comment by AbandonedCart** [comment]
I can honestly say I didn't particularly "need" this feature, but ended up leaving it enabled. This was a good suggestion.
