### ISSUE TITLE
[Feature Request] Ability to install extension in private 

### ISSUE THREAD

**Issue by Mathew20kdroid** [RepoDevil/Himitsu#35]
Please add an option to **install extension in private** like in **tachiyomi** so it doesn't show up as an installed app in Applist...

**Comment by AbandonedCart** [comment]
I'm not familiar with tachiyomi. Was it something you changed in the extensions or just an install option?

**Comment by Mathew20kdroid** [comment]
Actually it's in TachiyomiJ2K , a fork of tachiyomi (manga reader app)...
When you install extensions using private, the extension doesn't show up in the Apps list( doesn't show up in apps in settings)

![Screenshot_20240511-170435.png](https://github.com/RepoDevil/Himitsu/assets/71634955/d641c7b4-729d-4647-a9d4-557018a821cc)

![Screenshot_20240511-170505.png](https://github.com/RepoDevil/Himitsu/assets/71634955/9ad47b19-402d-4060-a457-5018c4f2dac7)

**Comment by AbandonedCart** [comment]
That is an odd setting.

**Comment by Mathew20kdroid** [comment]
I CAN NEITHER CONFIRM NOR DENY THIS😅

**Comment by AbandonedCart** [comment]
So the way they are doing it is way more elaborate than I expected. It's essentially a game of storing the apks and using them as needed. I think I may have another option that is far less expensive in terms of performance and storage.

**Comment by AbandonedCart** [comment]
I have a way to hide and unhide packages I will test out. If it doesn't work out, though, I'm going to have to skip this one. They way it's being done currently requires mirrored copies of the extension code and i'm still working to eliminate the unnecessary duplication already here.

**Comment by AbandonedCart** [comment]
My method depends on the app having a launch class. Extensions typically don't to hide them in the app drawer. That means it would require something like the intricate method already in use. That's a bit beyond the scope of what I want to accomplish right now, since it's essentially a part of your phone others shouldn't be wandering into.

**Comment by Mathew20kdroid** [comment]
Is there a way to archive these extensions like the one feature newly introduced in Android 15, so when the app is in use the extensions will be unachieved and when not in use after a delay period the extensions are archived....
