### ISSUE TITLE
[Feature Request] Bulk Notification Enabler for Anime and Manga

### ISSUE THREAD

**Issue by Mathew20kdroid** [RepoDevil/Himitsu#36]
Please add an option in the **Settings/Notification** to enable **Notification for all Manga and Anime**

As of now we have to open each and every manga or Anime and click the bell icon to enable notifications😣😵‍💫. 
It's soo frustrating and time consuming since most users will have hundreds of manga and anime in their collection....
So I would really appreciate it if you could add toggle in Settings/Notifications to enable Notifications for all Manga and Anime.
**(Separate toggle for Manga and Anime will be helpful as well)**

**Comment by AbandonedCart** [comment]
Are you talking about in your list or in existence? I assume a list, but... some of the things people have asked are a bit out there.

**Comment by Mathew20kdroid** [comment]
I was talking all the manga and anime which is saved to my Anilist account....

![Screenshot_20240512-213721.png](https://github.com/RepoDevil/Himitsu/assets/71634955/babe461e-3a38-474a-8408-5e6c04bdc8e0)

The notification icon is turned off by default for all Manga and anime at the beginning......we have to turn them **ON** one by one which takes too long
 
I was just asking for an option to turn this ON for all **Manga and anime in "my account" ** at the same time

**Comment by AbandonedCart** [comment]
For now, I'm running with what you're currently watching and reading. There isn't much point to adding things that aren't started or are already completed.

**Comment by AbandonedCart** [comment]
It's the first option in settings notifications for "subscribe all current"
