### ISSUE TITLE
[Feature Request] Manga notification/Subscription Notification in Notification Page

### ISSUE THREAD

**Issue by Mathew20kdroid** [RepoDevil/Himitsu#37]
Please add **Manga notifications (Subscription Notification)** in the **Notification Page**.I believe this is a long overdue feature.
Also a **separate section** for **Manga Notification** in the notification page will be really appreciated.

**Also thank you for all the work you have put into the app. I noticed you take all the features suggestions by users into consideration and is quick to implement them..... Thanks for all the hard work**

**Comment by Mathew20kdroid** [comment]
There is already this feature present in himitsu itself. While checking subscriptions we can get the newly released chapter numbers along with the respective titles of individual mangas, The only thing is that it only shows up in the notification panel and not in the app....

It just has to be presented in a tab in the notification section in himitsu, the release date can be set as the fetched date.....
(Also some extensions also provide chapter release dates as well)

**Comment by AbandonedCart** [comment]
There is no way to reliably rely on extensions for data because they are volatile, even per instance (they could be added or removed at any moment)

**Comment by Mathew20kdroid** [comment]
This is just my opinion but for me just having a list of the latest chapter updates is good enough for me at least and the date can be the date at which the chapter was fetched.....
Having a list of updated chapters will be good enough for me to catch up on the ones I have missed so far.....

**Comment by AbandonedCart** [comment]
I think the current notification you are referencing is the one you requested as part of the predictions. That's completely isolated from AniList. I believe they have a way to get the releases for the day, but nothing like what is used for anime. It will depend on how ugly the results are from that API and how realistic it is to turn that into a notification.

**Comment by Mathew20kdroid** [comment]
I was just referring to the notification we get when we check subscriptions from extensions, the one which only shows up in the notification panel...

**Comment by AbandonedCart** [comment]
Rather than fixing any of the bugs, it seems the upstream project added this feature.

**Comment by Mathew20kdroid** [comment]
Awesome, can't wait to see how it's implemented...

**Comment by AbandonedCart** [comment]
yeah...

**Comment by Mathew20kdroid** [comment]
It's not working on my end😅

**Comment by AbandonedCart** [comment]
Sounds about right. I'm working on fixing it.
