### ISSUE TITLE
[Bug] Anime Title and other notification elements not showing up 

### ISSUE THREAD

**Issue by Mathew20kdroid** [RepoDevil/Himitsu#39]
In the **Media Tab** in the notification section on the episode number shows up....
![Screenshot_20240513-161950.png](https://github.com/RepoDevil/Himitsu/assets/71634955/dbe2ec7b-d6d7-4c0e-8123-4acb337c790e)

Also in the social section nothing shows up unless you scroll to the part where a notification related to that is present in the **ALL** section..
This is also apparent for the other sections as well.....

https://github.com/RepoDevil/Himitsu/assets/71634955/eb3b2b5c-f26c-4b59-a579-82f2e6250208

**Comment by AbandonedCart** [comment]
The sections only split up what notifications are loaded, not load your past notifications. This is how it's supposed to work.

**Comment by AbandonedCart** [comment]
Apparently there was never a title to those notifications? Weird.

**Comment by AbandonedCart** [comment]
Three full size screenshots is a it excessive. It was already caught, but I was cleaning up a few other things.

**Comment by Mathew20kdroid** [comment]
Sorry , I will try to be precise next time....

**Comment by AbandonedCart** [comment]
No need to apologize. It's just a lot to scroll through. If you feel you need a couple to explain, it's usually good to wrap them in a spoiler

```
<details>
<summary> the label that you'll see </summary

(The line skip matters for screenshots) screenshot
Screenshot
</summary>
```

**Comment by AbandonedCart** [comment]
I put a lot of thought into whether the other tabs should get more content and it seems like that could just as easily cause a lot of issues. If you have one person that followed you a week ago, but 20 anime you follow releasing daily, you could end up grabbing 140 notifications trying to get something to appear in the followers. By refreshing on the main tab, you at least see content coming in.

**Comment by Mathew20kdroid** [comment]
Can we get an option to set like a custom number of notification to be fetched....
That way users who prefer this can receive a number of notification as per their wish.....

(will this consumer too many during resources)

**Comment by Mathew20kdroid** [comment]
Yeah, but that means we have to keep scrolling till we reach the particular point for the next section to show a notification....
It means we have to scroll first for a notification to pop up in the other tab😵‍💫😣

It would be best to set a custom notification fetch count. Don't care about how much resources this might take😅, if it's too much for the device we can always lower the count....
