### ISSUE TITLE
[Feature Request] Set Default Extension/Source for Subscription check

### ISSUE THREAD

**Issue by Mathew20kdroid** [RepoDevil/Himitsu#40]
Please add an option to set a preferred extension for checking Subscriptions for chapter updates.......
Right now whenever we install a new extension, it automatically sets that as the default for all the manga ...

So please add an option to set a default source for subscription updates.....
(The same for Anime will be helpful as well)

**Comment by AbandonedCart** [comment]
I think you hinted at the issue with this by explaining what happens. The issue with trying to set a default for volatile lists is that there are about 100 reasons it could fail.

The extension list can be rearranged, though, and it sounds like you already know it checks against the first one on the list. A simple solution is to work moving the new item below the one you want as your default into your install process.

**Comment by AbandonedCart** [comment]
Since this one is possible to solve using the current design with only minimal inconvenience, I think it's best not to add this right now.
