### ISSUE TITLE
[Feature Request] Old cards layout and some other Feature Request

### ISSUE THREAD

**Issue by Mathew20kdroid** [RepoDevil/Himitsu#41]
1. Please add an option to revert back to the **:old cards layout"** in the Home screen.
![Screenshot 2024-05-14 230500](https://github.com/RepoDevil/Himitsu/assets/71634955/6e781ff8-9f51-41b5-b233-066e15f446f6)

2. There is a small alignment issue with the "**Anime and Manga REVIEW Card**". when in Landscape mode if the screen width is more ( when using a tablet or a foldable) the review card stretches too long. It would look great if it doesn't stretch beyond the two cards above like in the image below
![Screenshot 2024-05-14 230847](https://github.com/RepoDevil/Himitsu/assets/71634955/75becbb5-58c5-4bb4-b43c-d925ba311f81)

3. Also another area which needs some minor fixing is the **"Cards transparency level in the Manga and Anime Section compared to the Home Screen Cards"**. The Cards in the Manga and Anime Section seems a **bit too dark** compared to the home screen. Matching the cards transparency to the Home screen will help in overall uniformity and also in the card visibility (right now the other cards are too dark)
![Screenshot 2024-05-14 232420](https://github.com/RepoDevil/Himitsu/assets/71634955/f66b8c3f-5453-4a96-80ce-8dbc424c152b)
![Screenshot 2024-05-14 232448](https://github.com/RepoDevil/Himitsu/assets/71634955/ce94eee9-89c7-4e31-bd3b-cb3aa6b241e9)

4. Finally please add a the **"dynamic banner or a background"** to the **REVIEW Cards** similar to the ones in Home Screen and Anime/Manga Section Cards .

These are some issues that i found, would really appreciate if you could take a look at these and fix them.

**Comment by AbandonedCart** [comment]
We’re not doing a whole elaborate set of options to switch between the old and new layout.

**Comment by AbandonedCart** [comment]
You did happen to mention one thing I've been thinking a lot about, so maybe you have a solution. The review button doesn't actually load any reviews until you click it. This means you don't actually know the contents before the button is pressed. So if I set the button image to random anime, what happens when that anime isn't reviewed? Or do I just request all the reviews and waste a query on someone who doesn't want to read them? Or do I just ignore the next issue report where someone says the image for the button was Naruto and nobody reviewed it?

**Comment by Mathew20kdroid** [comment]
Actually pressing the Anime/Manga Review button shows reviews for a whole bunch of Anime/Manags.
i was just suggesting that having a random banner is better than leaving it blank, which doesn't match the UI

**Comment by Mathew20kdroid** [comment]
> We’re not doing a whole elaborate set of options to switch between the old and new layout.

Is there a way to revert to the old layout?

**Comment by AbandonedCart** [comment]
> Actually pressing the Anime/Manga Review button shows reviews for a whole bunch of Anime/Manags. i was just suggesting that having a random banner is better than leaving it blank, which doesn't match the UI

Yes, but none are actually loaded until you press the button.

> Is there a way to revert to the old layout?

No

**Comment by Mathew20kdroid** [comment]
Please add an option to revert back to old card layout, at least on portrait mode, it looked soo much better🥺🙏.....

Also the floating icon kinda gets in the way , can you make it so that we can hide it somehow or it perfectly blends in with the profile icon , when not in use...

**Comment by AbandonedCart** [comment]
The old layout looked much worse and the icon does blend when not in use.

**Comment by Mathew20kdroid** [comment]
Can we at least have an option to switch between them ... please 🥺🙏 

I know I'm kinda pushing it right now, but I can't get used to the blades no matter how much I look at it😓

The **UI looks very uniform with everything being perfectly straight and aligned**, the blades seem of place no matter how much I look at it.....

So please please add an option to switch between the two styles🙏🙏🙏🥺🥺🥺

**Comment by AbandonedCart** [comment]
The best I can say is not to buy an LG TV then. It seems they use a similar menu style.
