### ISSUE TITLE
[Feature Request] Option to replace Subscription with Subscription Updates 

### ISSUE THREAD

**Issue by Mathew20kdroid** [RepoDevil/Himitsu#42]
The new **Subscription tab** added to the home screen already shows the titles already present in **Continue Reading Tab**.....
It would be better to implement something like in the image below......which shows the **latest chapter updates** and the arrow button shows a list of all the newly updated chapters....

It can be a small scrollable list which shows at most 6 to 10 chapters.....pressing the arrow button shows all the chapter updates.....
![Picsart_24-05-15_10-34-51-938.jpg](https://github.com/RepoDevil/Himitsu/assets/71634955/7b2ad080-1778-4f1e-993c-37f1867d456b)

**Comment by AbandonedCart** [comment]
I'm sure it would be better to do 100 other things, but the one we went with was intentional. It seems like this is another way to request chapter notifications, but there is already an open issue for that.

**Comment by Mathew20kdroid** [comment]
Nah, I just wanted to add a little bit more flair to the home....makes the home screen look unique

**Comment by AbandonedCart** [comment]
Rest assured, I am already making it unique.
