### ISSUE TITLE
[Bug] Anime Eposide card size too small

### ISSUE THREAD

**Issue by Mathew20kdroid** [RepoDevil/Himitsu#43]
The **Anime Episode Cards** are too small both in portrait and landscape view.
![WhatsApp Image 2024-05-19 at 10 48 36_f3d37237](https://github.com/RepoDevil/Himitsu/assets/71634955/2b00f53d-ec7c-41bc-9953-60594100c3c0)

**Comment by AbandonedCart** [comment]
Building now

**Comment by Mathew20kdroid** [comment]
Also just noticed the in the expanded view for sections, the cards are also too smallhttps://github.com/RepoDevil/Himitsu/assets/71634955/366de6fe-9f27-4005-9e8c-aa25070fe899
