### ISSUE TITLE
[Feature Request] Icon shape change for Manga Notification 

### ISSUE THREAD

**Issue by Mathew20kdroid** [RepoDevil/Himitsu#45]
As of now the for **manga notifications** the profile Icons are **round** which causes some of the profile image to be **cut off and there are some weird gaps**......

It would be better if you change the icon shape from the circle to a **rectangular shape** which will very well match with the manga profile images.......
Similar to how the app displays new Anime releases, but the notification being **not that big**...

**It will also help to differentiate the Manga Notification from the rest of the social and activity Notifications......**

**Comment by AbandonedCart** [comment]
It's only a circle because the upstream project recycled the user follow layout into the subscription notification layout. I am sure you are aware that feature is actively being revised, so there is little need to assume it's the final version.
